---
# defaults file for Grafana
state: present
name: apimon-alerta-webaddon
config_revision: 0
replicas: 1
image: quay.io/opentelekomcloud/alerta-webaddon
secret: alerta-webaddon-secret
fqdn: alerta-webaddon.apimon.otc-service.com
cluster_issuer: ''
ssl_cert: ''
