---
- name: Manage Executor StatefulSet
  community.kubernetes.k8s:
    state: "{{ state }}"
    namespace: "{{ namespace }}"
    name: "{{ executor_ss_name }}"
    api_version: "apps/v1"
    kind: "StatefulSet"
    apply: "yes"
    definition:
      metadata:
        labels:
          app.kubernetes.io/name: "apimon"
          app.kubernetes.io/component: "executor"
          app.kubernetes.io/instance: "{{ instance }}"
          app.kubernetes.io/managed-by: "operator"
      spec:
        selector:
          matchLabels:
            app.kubernetes.io/name: "apimon"
            app.kubernetes.io/component: "executor"
            app.kubernetes.io/instance: "{{ instance }}"
        replicas: "{{ executor_count }}"
        serviceName: "{{ executor_svc_name }}"
        template:
          metadata:
            labels:
              app.kubernetes.io/name: "apimon"
              app.kubernetes.io/component: "executor"
              app.kubernetes.io/instance: "{{ instance }}"
          spec:
            affinity:
              podAntiAffinity:
                preferredDuringSchedulingIgnoredDuringExecution:
                  - weight: 100
                    podAffinityTerm:
                      labelSelector:
                        matchLabels:
                          app: "apimon"
                          component: "executor"
                          instance: "{{ instance }}"
                      topologyKey: "kubernetes.io/hostname"
            containers:
              - name: "executor"
                image: "{{ executor_image }}"
                imagePullPolicy: "{{ executor_image_pull_policy }}"
                command:
                  - "executor"
                  - '--config'
                  - "{{ config_location }}/apimon_executor.yaml"
                resources: "{{ executor_resources | default(omit) }}"
                volumeMounts:
                  - name: "apimon-config"
                    mountPath: "{{ config_location }}"
                  - name: "apimon-secure"
                    mountPath: "{{ config_secure_location }}"
                  - name: "wrk"
                    mountPath: "/var/lib/apimon"
                  - name: "home"
                    mountPath: "/home/apimon"
              - name: "statsd-repeater"
                image: "{{ statsd_repeater_image }}"
                imagePullPolicy: "{{ statsd_repeater_image_pull_policy | default(omit) }}"
                command:
                  - "node"
                  - "/usr/src/app/stats.js"
                  - "/usr/src/app/conf/config.js"
                resources: "{{ statsd_repeater_resources | default(omit) }}"
                volumeMounts:
                  - name: "apimon-statsd"
                    mountPath: "/usr/src/app/conf/"
            volumes:
            - name: "apimon-config"
              configMap:
                name: "{{ config_map_name }}"
                defaultMode: 420
            - name: "apimon-secure"
              secret:
                secretName: "{{ secret_name }}"
            - name: "apimon-statsd"
              configMap:
                name: "{{ statsd_repeater_cm_name }}"
                defaultMode: 420
            - name: "wrk"
              emptyDir: {}
            - name: "home"
              emptyDir: {}
