---
- name: Manage Scheduler Service
  community.kubernetes.k8s:
    state: "{{ state }}"
    name: "{{ scheduler_svc_name }}"
    namespace: "{{ namespace }}"
    api_version: "v1"
    kind: "Service"
    apply: "yes"
    definition:
      metadata:
        labels:
          app.kubernetes.io/name: "apimon"
          app.kubernetes.io/component: "scheduler"
          app.kubernetes.io/instance: "{{ instance }}"
          app.kubernetes.io/managed-by: "operator"
      spec:
        type: ClusterIP
        ports:
          - name: "gearman"
            port: 4730
            protocol: "TCP"
        selector:
          app.kubernetes.io/name: "apimon"
          app.kubernetes.io/component: "scheduler"
          app.kubernetes.io/instance: "{{ instance }}"

- name: Manage Scheduler StatefulSet
  community.kubernetes.k8s:
    state: "{{ state }}"
    namespace: "{{ namespace }}"
    name: "{{ scheduler_ss_name }}"
    api_version: "apps/v1"
    kind: "StatefulSet"
    apply: "yes"
    definition:
      metadata:
        labels:
          app.kubernetes.io/name: "apimon"
          app.kubernetes.io/component: "scheduler"
          app.kubernetes.io/instance: "{{ instance }}"
          app.kubernetes.io/managed-by: "operator"
      spec:
        selector:
          matchLabels:
            app.kubernetes.io/name: "apimon"
            app.kubernetes.io/component: "scheduler"
            app.kubernetes.io/instance: "{{ instance }}"
        replicas: "{{ scheduler_count }}"
        serviceName: "{{ scheduler_svc_name }}"
        template:
          metadata:
            labels:
              app.kubernetes.io/name: "apimon"
              app.kubernetes.io/component: "scheduler"
              app.kubernetes.io/instance: "{{ instance }}"
          spec:
            containers:
              - name: "scheduler"
                image: "{{ scheduler_image }}"
                imagePullPolicy: "{{ scheduler_image_pull_policy }}"
                command:
                  - "scheduler"
                resources: "{{ scheduler_resources | default(omit) }}"
                ports:
                  - name: "gearman"
                    containerPort: 4730
                    protocol: "TCP"
                volumeMounts:
                  - name: "apimon-config"
                    mountPath: "{{ config_location }}"
                  - name: "apimon-secure"
                    mountPath: "{{ config_secure_location }}"
                  - name: "wrk"
                    mountPath: "/var/lib/apimon"
              - name: "statsd-repeater"
                image: "{{ statsd_repeater_image }}"
                imagePullPolicy: "{{ statsd_repeater_image_pull_policy | default(omit) }}"
                command:
                  - "node"
                  - "/usr/src/app/stats.js"
                  - "/usr/src/app/conf/config.js"
                resources: "{{ statsd_repeater_resources | default(omit) }}"
                volumeMounts:
                  - name: "apimon-statsd"
                    mountPath: "/usr/src/app/conf/"
            volumes:
            - name: "apimon-config"
              configMap:
                name: "{{ config_map_name }}"
                defaultMode: 420
            - name: "apimon-secure"
              secret:
                secretName: "{{ secret_name }}"
            - name: "apimon-statsd"
              configMap:
                name: "{{ statsd_repeater_cm_name }}"
                defaultMode: 420
            - name: "wrk"
              emptyDir: {}
