apiVersion: operators.coreos.com/v1alpha1
kind: ClusterServiceVersion
metadata:
  annotations:
    alm-examples: |-
      [
        {
          "apiVersion": "apimon.otc-service.com/v1alpha1",
          "kind": "Alerta",
          "metadata": {
            "name": "alerta-sample"
          },
          "spec": {
            "foo": "bar"
          }
        },
        {
          "apiVersion": "apimon.otc-service.com/v1alpha1",
          "kind": "Grafana",
          "metadata": {
            "name": "grafana-sample"
          },
          "spec": {
            "foo": "bar"
          }
        }
      ]
    capabilities: Seamless Upgrades
    operators.operatorframework.io/builder: operator-sdk-v1.2.0
    operators.operatorframework.io/project_layout: ansible.sdk.operatorframework.io/v1
    repository: https://github.com/opentelekomcloud-infra/apimon-operator:0.0.11
  name: apimon-operator.v0.0.11
  namespace: placeholder
spec:
  apiservicedefinitions: {}
  customresourcedefinitions:
    owned:
    - kind: Alerta
      name: alerta.apimon.otc-service.com
      version: v1alpha1
    - kind: Grafana
      name: grafanas.apimon.otc-service.com
      version: v1alpha1
  description: Apimon operator Open Telekom Cloud
  displayName: apimon-operator
  icon:
  - base64data: "iVBORw0KGgoAAAANSUhEUgAAAMgAAADICAIAAAAiOjnJAAAqwElEQVR4nOydd3wUZf7Hn2fKzvbsZkMChJ4gvReVGkCQKigcqMAhduQ8T9Sznif+PHs7G4oFOBQLUiwEpffeW+gEQkjZzfY2/ffaTAjJ7mwKu7MlzPvFH2HmmZlndj/71G/BeJ4HMjLRBol3BWQaJrKwZCQBi3cFkhyO50mGp1jA84G/WR5iEKAIQCCiwIACjXf94oYsrPrBuUn6RAl98Ap9rJi5ZOeKnGyJi3P6AcXxNANoDioxoMQhgSEGJZKmwVoZ8W5N8fbpWLtGWHMDVOHxfoMYAeXBe63wfprceoHceZHcdI4+XsKVeQBb/w9NgaJpGmJwlnJMe2JwFtZUDxAoSXUTA1lYYeF9NLXvsnfVCd+SQ2yBPZq3RiHevalqQmf15G74TY2ieeeEQRZWMJzD71uV51txjNqRzxY5gaQfjxIj+jQnhmUTQ7IVvZshaoWUD4spsrCuwVx2uD/d7lmwjytxxf7paCtjyn9Gae7pARpEDykLKwBr8ThfW+eZv4v3MfGtCTEkK+Xfw4kBrQNTy2TmhhcWD8jtF2yzV9BHiuJdlatgiOrOzikvD8c7N453Va6fG1pYbInL8cJqz+IDgGbjXZdgoBo3fDRBO7Nvkq5h36DCYoudzjc2eL89wFl99bsShYhJg7dPR1unohlatJEWaaJDUpRQhUMCC7SADAdIhnOSnNPP2X3sBStzwcoW2JkLVt5D1W8qgEDl7e20TwxQDWsLsCTT140oLOaMxXzHAuZkad0vQQwqRf9WymHZyqHZeMcMgNd7SV1YWfWtOOb7+Qhztqxe16ru6mL8ZALaRF/fh8aRG0xYPPAuO2J7fCVXXLd5HwxM1rSPD9BM7Ymma6NSBc5H00eKfMuPehbt40rcdbwKbZvWaOUMvGPSjLpuJGExrOPNjc5X1wKaq7UsVGLE0GzdY/2I4W2hQpKNL95Luefvdr69kSuqk8qxjhnpfzyINjdIUZmoc6MIi/czttnLPQv3Aa729yVy2hj/OwHvnAEQyUc2rMXj+Wq3+7MdbIGj1sJY+/S05TPwDulS1ypybghhcW7S+sBS30+Hay4GlZhyXEfN/X0Cg+X6j6IigfPS/tw859sb6b2Xay4JU5Qpc0foZvVLcNOJhi8szuo1j/uG2nGxpkIQqCZ0Nrw9BstOi13NQmE453ubna9v4J3+mguqJnczLb4HJrC2GriwOJvXctcictP5mgpBoJ0z2PjW6ARZ7KZPlFhnLaO2XKi5WMp7Y/VzBseqUvUmmYXFA55keJoFJMO5KajCoEYBcVRYTxLGVZYp3/p/PV7DPaAaT3ljtO6xWwGWQL9+3kc7XlvnemtjDfY50KDM2PIY3qVJbKtWV5JPWJzNRx0sJDefI7flMydLWbPn2rq5GkczdFi2SdE9UzW2g2fRPs83e2u4FZqpNy2ZSgxqE6Oq1xPH3DXOV9bWUADNNmWsewRtaYxhpepK0giLuWjz/nTYt/I4fbyYd9QyBAHlHVxNy9wYop11q/6FYWhjXVSrGVVYzrN4v+Pfa9hLYa3BsLZpaStm4J0Sbn0rCYRFnyp1vrrOu+woIKNmeqB7fqjhP6OSwkCFLXRa7lpE7bkUrgDa0pCx5TG0RWK1WwktLN5PO1/f4HpnE++PpjWLcmyHtGUzEnlKFQRrdltGf03tC7sSoRiSlfHnQzFeIqmZhJgHiUOx1keWOf9vXXRVReRkmb69N4lUFWiTGmnTfpmJtk4NV4DaeM6XezK2laqFBBUWa/GYp3zr/d/+6N5W0be56cdpSIoyureNAWhTveH1mvpu1/tbpLWirieJJywe+HLzSm/52L/yWHRvTAzJSvt1ZrT2kmOP+i9dDe+ODdffkVvOO9/dFPNKhSXhxljuL3bZHl9ZR8s7qFWgLYyIUYWocM5LsVecbKFT9FqsbVrG3ieSsa0KwvnWRsdzuaKnoBJrtPFR4paWMa+UCIklLGr/5dKBn/E+uuZiiFGlHNdRM62nom8LqMah8CMuXy/lnH5qb4Hv9zzvkoNVN0aMX/1F+0BfyV9AeniSsUz8n39VnuhZxcDWGesfSYRRfCIJiwfm8Qv8v52ooQja0qj7W3/1zD6oSV3zzZizZfZ/rfavOM6TjKJ3s/QtjzUYL2S2wF7c96NwJmWmpdPVk7rGvFLBJJCwfLl5ljsWAjassZRydPvUbyajGXVe0mQ56kCh873NKf+6LQGXECPBvWCP7f6loqfw7k0b730i7qbMiSIsOq+0dOjn4X6F0KjSv3SbbtatDabViRSWM4/7xr/6lMgpCAzvjtXFe386MWaFFGt9cGk4VaHNUjK2ztbPGSSr6hooovvnEPHVBx44/rOBs3ljX6mqJISwfOtPU7vE7aWgQWVaOh3vlBHzSiU6RL+WeI+moqd4q5fcFXYLKDYkhLBc728VtxiGwPj+uASZPycaUIHpXxgWLmSNf3WcF+LjLyzmrIXcfE70lKJXM81fe8W8RrXAWr28t5YFkdigGtsRC2P/7l93BjC1+4xIR/yF5fp4Wzi3mcAwIjGsOithS92WCQtLc+ZRBwvjXRcACczw5mjRRos5bSb312I+Lylx/tp4P+37RdzCE22dqhrXIeY1qgnmfFnp4HnU1gvU3oLSwfMSYd9XNbqD4laxoQLLe+bvikOFrhJnYbFFrnBuT+op3aAygaaBTL7VPPqrSv9p3kWWTVnsyxVfAY8dCNRMFx8t+H49Tu0tiNfOdJyFxVy0hRu2q8YmUHNVrqqvmVOWqgd5N1V2zxLq4JX41SuA6o6OiEEVepyzeEsHfVY2bQlzwRr7WsVbWKfEAyggaRq8c6K4CbAlLvPtXzJ5IlXlnX7rQ0s5FxmPelWANtEr+rcSPcX7Ge+Sg8Xd3vcurcWnMurEQVicm/RvOOv41x8lg+fZ5/wmWgZrn54glghsicvyl8XMaUu4AvT+y6VDP6cOxHMsr57ao4azgV576pKy6UuoGMYAi+2WDst5vjvoeG4VW1u0AvWMXqaFd8eqWmGp6AHF2qogoF5pWnKvakx8um/OTRZmzAW1LYJAJaZ/dYT+ycEx2EmMXYtFHSg0j/3Get+PtapKCBsUk0rVBHO+zDzyq7qoSugTy6Z8G6+xPKIlsPCGy5XwfsbxbK71oaU8JXlEzFgIi7N57c/8XtLvE/8fp0DdGkgY7+Wrq6N1c90v4T1U2d3fUXFaPdLc2wOq6zCJ5oFn4T7nf9ZLXR/Jvz/6ZGnJrZ+43t1cP+ctGE/PLLbUVV9VCfAu0vroMs4dh7G8/vmhjY88pfvHAKipPaa3882N3hVHJa2PlMKiWc+ifaU58+r3DUEA1TiSVosdn3QERuuTFtexBwyF3nfZnDOPOhDzdgtCLMtk+GB8k4svpi6cHG6rpwKKLbt3ifONDTVYv0VaHYkG75zNVzbzB/+vJ+q6QIciWOtU5Zj26old8G5NEX18poSBHvD2L2uYA9YRqFWYvp+qGtsxSvWqN5zL73g21/3l7pp3DHXP5hjeGCOF464kwuIcPsv4heTmGmO8CCCQGNhaM6O34paWWOtUqIxn0qi6zwHrAtQTpiVT4zVPBEJczKWHbY8s4+zhA/jiqGnx3eop3aP+8OgLi/dS5jHfkJvEDRaugUJiUBv93BHKgQkRk4O5IOzY1HtcVQNQjadvm63okRnFe9YX+nixZfK3zImScAWgUdX4yFNYs5ToPjf6YyzXR9trURUEir7N01bel77m4QRRFWt2m8d8HV1Vlf/GaOtDP/OeeK7L450aN1r9ANom7GIEb/O5v9gZ9edGucXy/nzEOuOHGsyV8C6NU94eo7qtbULFo3J9up3cWkugMwH68JVK/SnHdazLDF/Ru7n+8f6AiGcvTx0stNy1iM23iZ6FKcqMrVEOtRVNYfnWnLbc8Q0gw/qaqiZ0Sl14d4Ls1Vwf9udzXW9uFP5uevklNDPKPYh00CdLS4eEdVdR3Nw8ffNjMHrqj1pXyJo9tlnLa1CV5uFbTEumJrWqkhq8fXrqorvDNbHUngJvbcF/60WUhMXx9udWsefDJFxAoO6ZnNRPJ8huNvFFNfwm3ZxB4ud44HpvcxQD+0RHWOT2/Boiw2gevNnw+siEGlTdoECge3Yo3ruZ6En6cJF32ZFoPSoKwuIcfuuDS8MtxKkmdjF+NF5WVYKAaBWmxfdAHSF61vnq2loDZ9T1QZHfwrfyGHNafKIOtYTxv+OjOCSUiRy8fboqTHAH5rTF892BqDwlGsJaESaQFQQpb4xKonnTjYN6Srdwp7xLDkbFTD5SYXF2n3+r+NYNMbC19uGbI7y/jBQoB7ZGUsUt3qi9BaylrjnJaiBSYXl/O8GL5pJEoe75YRLlzZKJEKhWqCaLN1q8m6KPFUf+iMiERbOeT7eLnlFP76Ua3jaim8tIie7vA0DYNa0oxH2ISFjU0WJqd0HocajEUl4enmhOzDJVwdtnED3Fd8epA1FwaIvou/f/Ie4KrBjYGkvIPBwy14CAGHGT6Bk2Pwp+iJEJa90Z0eOav/YKFwVFJnEgBrQWPc4UOiIPKHL9wuL9jPgoT4ESiWEMI1MzWHYawER+/7yTZGtLmFgr1y8sOq+Es4qEjcOapUTdakxGCrDMFLSpyDfFeyjO4onw5hEI62iRaDY9vEsTedieHCAQFW0COJ694oz03td9JRPGagxppImgPjIxJZzTSuRmDtcvLLZUfH0WpsbNc0umvsBw5nH+SLeiIxi8h/H9QE0NusVKjOjlUSOcX2HEg5kIhBUmvmPDXmhQ9GomeOFhbdPC/tyTB84m3jrAiP06I9jLC6cfpk75lZIU9aRu3Dwfk2/VzroV0YpbNSURXJl4OHgkJdJXu35hhftY+bgG65UcCLSP3BLvSkQJmhUP9ocjSMQD5evvCsNZIXJhBvUyiQZz2cGLxS+BWgIxxk9Y4VZBw80WZRINOq9EdCUSMaoi7+UjEFa7RqLHmXC+OjIJRjjTXyzbFHmYkOsXFt6tqah3L5NXyka8ISAjNZzT7w8Tp17RQ9yNp15E0GI11aPpIktWvJuiDsU/a4NMzZA7L7JhvKLxmmNr1Y0I1sFQRHFzC9Ez5B9iefRkEgnPon3hIuxHJYhDRAusxOAs0eOe7w/xHiqSO8tISqAfDJNVGknX4mFGz/UiImcH9Z2dHS/9wTuCbXe4K073/F26J8N4c1eFZsm9BdTuAuaMmS1x8W4qXik6khsIoI7AWhmxDhlEv1YBZdS4/+H97gDvFA+upJ7Wsy5RTGslImGhmSmq8Z1Enesdr61XTeqKNTfUcDmdV2qbvZzcWFuINpl6AQGRk2X8eELYNNgs7/p0h/ilSkz3t/5RqUWke42aqT1EIxzzVq/rzY1hmx+O9yzeX3Lrx7Kqog8PyI3nzCO/CjuFYtlw5laqCZ2xVrXHi68LkQqLGJQlbixWPjykz4q53jOcY+4a6/0/hfahMtGCvewoHfKFf+1pkXMKTHVnZ5HjKKL9x8BoVSBSYUElFs7ZA+oIJFVkPcL99W7nfzbEN//njQBv95VNW0IdFvHlEnWxJ25rS/SKwgqWQBRsiLUP9RXNzaKb3Q81BW85kdvzbU/8Il14cZmqcKUeyx0LQnealQPboNX985AMrfHjCVHMsROFGxF9W6rvCck+pcTUU3uGFnZ9uLWGqH8yUYe9ZLc9+WvQkhVU4ZoH+lY9YnhvHN42LYrPjYZCIUh5dUSQsQOenRbqs8o5/GQYV0QZ6fD/cZIpsAcdJAZdcyrEe2VqwoRyuG6iE7QDa5Wqf/k2xzOrrh3pmB66lEJuzw8XzB5tlqKbM0jRuxlAZA+fesNTjH/DOddbG8TTtpMstf9y0O8c75ABDSrBvlz394EAj3JkvKhFg9E9PsCfe7Jy+QBvJ7LfRIYJeIS1TUvf9Kioj5tMHVEOySb6NLNMXiw60mBOlIC7ulQ9gqZp0HQtY/fhPTLV0W6uohk1GRKYacnUyhyyok5gdJj8CIaPJsiqihzVuE6a+/qInmIuh2R0RyCaqVcMbpO2coYUmWai2e+gjXWNfpmJZpkEY7HQAnwY031FmLAnMvUDAkWf5qJneK/I1q1ybMdGv87EWkgSviXKAxrEpDa8PgogEIomHAznO9WgHXtiSrg8j2IfvP4fA6XLshb9NlA9sQv11OAG5n7XMJHy9yxBKEcUMbwxig3T68ncIEgzt0cRNK1B+0PL1EbyLRrxXoo+Y2aLagmHwprdzDkLT9W4ys9wzPkyJt8qbkt5Fc7ho0+b45LpOXlJsqjG3p+P2J9ZxRbaoQrX/+s2/dM5IoU43j1/l+Nff3AuEu+QYfz0TqJfq9BS1OErtkeWUYeuQASqp/dMnTdRdMzh33reOv0H9ooDbaJPeW2kZnovSV6swZFMwqJPm8umLREWAHmadLz0p3LETYquTYOKeX85bpu9QmiE6ENXLGMXNM57Gs3QVS3DuUnLuAVs+UYHD4Bn/m7i1pahi0DMOYvljoXC8jR7yW59YCnSWKcaLm7NES14P00dKCS35XOlbjRTTwzOUnRpHPWVcalJJmGRG89VW1YmGc/C/Yr3g4Xl+Xxn1a6Ns3m9PxzSPVHN0ojad5mtvn3mnrczVFieJQerBdWhWc+XuyUVli83z/HSn/TBKjZ6CCT6t0p5YzTRX6TdTViSaYwVmj9I1EOccwUfDD0SGlhMdAjFu4LXFfmQW0UR51sbLXcsqKaq8p6d3HqhdNgX7m/2SvfoqJNMwiKGZQNFlR4BRzT39Q4tpn3klqrrhFBPaKYFD4yIW1og1eN4aR/rF3orzbSe1TJHolDzoFRJXKhDVxwv/SHq8w7Km2f731eGi6KYgCSTsBRdmhg/nlCxWYRC3VODRUflmmk99a8MB+X7X2hLo+nHaVir4F0LxKAy/Twdu2qBpJrUVfewSAwZvGuT1AVThLQzMEWZ8vpo9YROkrwbAM65a2q2quU9lOu/WyR6etRJpjFWoF15+Bb1xC70GQuSqsbLNyVFQJGUl4drpvXkyrxYh/Rw8S2UOVmNDz1J55UCDFF0yAg3OlZP7kYMaM1ctGFZJjRdG82XqQJrdvvr4Ffi++mI8b3xSdEaJJmwyrcjNUQdolFibUygTRjlXQWqFYo6WHmjTfVoU3196lhvmAu2uriWsFecrMWFpuskrUxUSAbx3wCIWh+Il0wSF3NZWAkB1sIA6mAUBdU41qwmH+DEQRZWQoC1NuGdwzguV0E5sl2yrJQm2RiLLXY539lE7b6ENtLoXx6u6CFuIcicK7O//AdX6CRub6f7W39ELKol76NdX+zy/3ocoIjuyUGq0e1Fb8U5/I4XV1MHryh6Zeqezgk0LVIAgf6ZnLIp39ZUBoVRdCiVmmQSFufwlQ76jDljEf5LHbzS+OCToaaqzBlzyaDPuGI3AIDcfJ7881T62oeDf+gsVzZtiW95RUg7aufF9G2PKboHy5T3UJZx35BbLwTK7Mj3/X4ifdMsiUwu1RO7uPq1pHZcDFdAOaq9sr94vq4EJJm6Qu+KY5WqCmjjos35/ubQYrZ/5gqqEiA3n3cv2hdUhtxTUKkqQUD2Ob+F3sr1+U5BVRVPvGBz/HtNxO8RBhRJXXyPcnT7aovAAkpMdXf31C/Et8kTk6RqsczBESjZS8HucuUHg5enmZBiodmtwtwq+GDozaMI3sbUaNUD1LFi73cHqO35XJkXydAph2Sp7+2BhVu0S1SSSVihw1vlEJHIb8qh2fSBwpqL4Z0yAr/+KnvVxNDs0FsROVnuj7dXNdUnckSKRRdF58aKN0YDIRUDlhxD9VCSqStUDstW3tGx8r+KfmKu/QDonxt6LYYlArVPDFCGqAFrbdI9P6QyYwza3JDyf7eH3ko9roN6Wo/KEMKKQa11j0cnfFSdSFpVJVmLBRVY2o/TfcuOkHsKkHSN9v6+UCxsM2JSN1rzkPvL3Vyhgxh+k2rETSLBpSEwzL1dOaytP/ckQKHmvj5BBlsVYKjp68lEThZ96IqiZ6Z6cjeojkK0uxuBZBKWEDVJPbWnaLiRqiB6pf6pwbXcC0WUQ7KVQ2rr2nBUe3/f+tZTJpm6QpkkQhaWjCTIwpKRBFlYMpIQU2GFy0THnLXEshoNmLAZsiSIJ1MzMRUWliUejNDx8p88GWnadBnmrMUzf5foKaxxrG0DYypkxa0twCfbQ4+T685YJi5KmXs7lmVKou2wBILn6cNFZTN+CN31EsCiGl+0LsRUWMSgNoE2OcT1CvDAv+qk/49TSKoGoLKw6g/Hc1ZvWF8MBOIhhhtSE1NhYc0Mij7NqSr2AtVgec4sZ2eNPni3JopoZIqrF7GeFer+MTBscDAZCYBaInXexNjbncZaWOrxnTT3i3iZykgCjhq/mBguraSkxHwdC0UM749XDm8b6+fegCBQ/69hmru7x+XhkI9HUEfO6bf94xfvwn1ydkKpIDDje+O0s26JV9z8+AgLlEducS/Y63hxNWfxxqcCDReoVxr/O14zo3fkyeivvw5xE1Y5bLHLu+wItfsSc8bClrjr7rcpEwTUKLCWRrxjhqJ/K9XIdogxOD1WrOsTX2HJNFTkTWgZSZCFJSMJsrBkJEEWlowkyMKSkQRZWDKSIAtLRhJkYclIgiwsGUmQhSUjCbKwZCRBFpaMJMjCkpEEWVgykiALS0YSZGHJSIIsLBlJkIUlIwmysGQkQXIXe55kqP2XmXwbYFg0M0VxS0tEk0DxYTkXGZrGNwjUoKzVk5jzULyXrmPhSlirF7A8VGHhkiomL9I6U9BHiqwP/kTtvVx5BOuQnvrFRGJgG+keWi/KZvzg/d/+msukb32MGFBLrhH7s6tcb28CAGTserzunsdFHd9h8kq1/xho/OCOOlc5OZCwK/SuOFYy6LMKVWFI4B8ATF6p+favPCE5SGQaGFJ1heT2fOu0JbyXRkxq47y7lCPbA573rz9je2wFV+yyPrIMbZqSCI72+mdyNFeDe9NnLfbZK4TsbbonB1WWwTvVnvBNJghJhMWWuMqmfR8YcyAw9X/3VGZsU9/ZBTGqzSPmA5Ipm/F9xt4nsMwUKSpQd/DOjSszqSBpFRmB0cwU5Yib4lqvpEeSrtA9fxebbxUS1ATlAVTmZKkmdA6Mdotcrg+SJie7TH2RoMXigX9VnvCn5l6RXDeae3r4lh4BAPhzT4K3xgAU8X5/yPv9QQCB7vmhrrc2+jed511+NDNF/+/hwVkhWM7z02H3R9uow1cghipH3KR/fmjVhOGOuWvp/ZehntC/MMz+1G/klvM8wyl6Nzd+MiFc1sw6vhS5+ZzjzQ3Uzos8xRL9W+meGqwa2b6W4Ags53x/i+vDrVyxCzEoiZwsw1tjsOywURs5N2V79GfeSQIM0b00jOjZTJi3er7a7Vm8nz5RAhWY4uYW2tn91eM6VCYC8v1y3PP1HrRNqu7pHMeLq30rj/N+Wv2Xrqnz/8IzrPOtjZ5F+ziLh8jJNrw+UtGz9uTqUSH6wuI8JC1kFYRA0VdkfoT3biZk3mILHKzDj6aq6dNm328nAATUsWL2vFUoxl6y2x5ZBrWEZnK3iitZzjbnV/dHFVFMecD4lh31/3nKtGSqalxF8iZq9yX/6pPQqKJPmel9FbNRake+9b4fMvY8IZp7py64Pttun/MboFjhv+T6s+Tm84a3RuvmhE+swnK2f65yv1/RKnNWn2/5MeZcWfrW2aIZXwEAzrc3eL87GBj5vXo70SOgANbisYxfSO3Ir3hlkiXXnSE3niWfGGh8Z6wQr5W5YPX9dgJrm+Zfe5o5USqU9H53EGmso48Wk2tOV9T5z1PmfQUZux6vQdlRJPpdIU8ygd8cAFBDIOkakUcaVdCgFFK3C2s/V68E7AWrcmwH4/xJuheGIqlqwHD22cuZgoqkgf5tF9yf7Aj8GjpmpLw/Tj93BNQqeDdlfeAn5mK1NIK8zcfklepfGGr8fKLi1paBgfnRYv+Gs9f3RvQ5i+OZ3wHFIk31KXNHpLw7FsnQBur23Gpyy/lwV3l+POz+71aAQs39fVIXTNHNGQS1BH24yPHyn6Llya0XXO9sDjTbLwxNeXGY0BZaH/lZUBXWrpHh4/HaOYOgRgFY3v3hVn/1RzNnLOw5q/bvA4yfT8S7Nw0MSD7YSq45TQxva5w/SVk+IOHKvK7Pdl7fh1BfJOgKOV6IsgoJDIolRoMIhAqMF0pWX0VTTeme9t1UQe2a6b1KbvmYs3idb25I/fSuwCc1bxfgeGJg67Tf70f0AWkqh7c1D5/PmT3O19anfjmp6q0Mb4/RPtYvMGOY2rMo+w2uxE1tu6AaJZ74uWY8X+7mfQzaPCV9x+NYsxQhzW5pzufsRZv9hdUZm2YJKynVPgOr1/7M74DldXMGGd4bV/F2k7uV5sxzf75T+/DNeIeMysI8y7m/3GV/6ncIofHryZq/9hKaInJfgX/FMSFtYtqvM4V2TnNvD/PIrziLx/35TmVOtTyMpp+mqe7oFCg/JKu483uAZpVj2jdafh9QoMpR7Yqy3gQUS20PEwA22kgweIdQ+Fx4iuEZNvQ8z/MVxyEIGqOop3SrrBHePl1IYOlfdZL30YDlqG3nyz+1bOaMhdp/mdp/GSowrG2jwDhj5THAVosZTFxdy0C0Cqy5obyBpK/vhchN5c8d0JorcQnP5cq8RHlDSO2+xJaJxPfyrz/DXXEGJphZJuGSQG0xBG2qB37Gl3uyWuGfj9geWc67SO1TgzQz+1QOnqjt+UJgOv2Lwyp7T0WvZuq/dA2c3XWp6k2gnhBUFXhouhaWZwxQjeogJAJGDCrhDrwvRvH0o99iQQUKdQTv8PNukivzoo20QQV4F8Xb/IGSKgVU4dVqU331AW1lLG/APTzJcG6Ssweucr661vnq2qB7chYP56GEZkwg0JNGBYZjiwMSKZ9hHBI9i2YEvyN9dawjLIwFX3S6WiYOtsgl/EHtKah2vLQ8aDsKg1LLYu3TA69s91U9KDp8hNq47Z5FX1iBFqKlkT5SBHhAHyzE2wcHgqYOFQqtC5qpRw3VctAH6aziwxJ6S44XMu0iTfSIBg99blDrCKMVm5mv6NmRVJWoWCEq1urTFZVBm6XAkHQjod832tLIXrKR68+QO/KJfq2uPbo8/WdQVwuFbOSJHddMgjEWghCD2wSEBYD3l+Oh2XV9vxwX/iCGZIPq3wpb5qkqGaGJAjgS6F5xVMgtkDrvTtX4ztGvdjhQBCoDldLM6md4bWQdL4Lqivcw/TRd6DRrQHFry7RlfzWP+Zo+eMU+57f0TY8KTxR+V7yP5qxeNO3aNIizBjpfiCe0ZYokldM+MRAxBX7cvmVHqT3VhgL0kSLPov3CmED39KCgC6kdF6sUZcntgQmRomsTRKtAU9VoG5OwBVn5Y+X9jP35XNvs5c53N0vxIqA89jBWHn3f/+epynYIcLzr/S222cvtz+dWrkFUhRjWVhg+Vnt9krE/87tt9nL6aFHVwoqbW6BN9KmL7oFaBbX7km3Ob8JxvHPFAN/7/cHKwryX8i4/KswTJXjbqCGJsPAsk3H+pEBrxHCWyd+SO/KBnwE0Sx8tskxeDHw0QKDxk7vwtsEfjev9LdT+y4DhOLvP9mwuc6wYQKB9fIDQsKnGBwan3sUHnO9sDAy5vJT9md9cb250f7azoneQBtWEwHPpfZfLZi1jLR5AMe55O+3P/O7+bCdn9gCxRxO9mwW0BYDz7U10XglgOc7ptz+X63p3s3fFMbRVauglii6NNTP7Biah83Z6yg0ulMNvQtICv0/na+s9C/YCimHLPNZHl9H7CwO1ujOGzXb9kWoTWj2hM/PGKMcLq9mLttLB87AWBoCjzAVr4PeNQP2zQzT3isQf52zekv6fYm1SOauPK3EJP3311cmOdmYf90fbeIff8Wyu+6PtAEfYfFtAx70yA5MpyVBP6up8fSN7vsz79V7/L8cRo5o5awE8QNK1+peGiV+DIob3xppzPueuOIt7foi1TuUc/sA8EQLDf0aFWyDVPNDH/dl2wPKOF1crR7ZD07Upb4+xPbQMMJz1gaXO1zdwdq8QZBpJ12im9ZLulSNHsn4agfqnBpt+nIY01gGGY85bmVNmQLFIujb1f3envDYSiI15Nff1ASzH5JUKqsK7NjF9P7WyScBap6b9ch/aOjBVZAsdAVVBWD5AmRHuq4rOq6SoGq26X3FzCwABZ/EyZwKqwrJNaSvvw8TaHgFF16Zpv85EMrTAzwTeKKAqqH7wZs2MsIk5FF2aqO7qEni7yw7HK2sAD7T39TXOnxgYV/A8c9YSUBUEeJcmjXIfRGOeKa5eSB41mS1x+VYeYwrsgS+jWYpqfGe0qT6ojGPuWucrawAA6ZseBSqcXHeGc5JYK6NqSjc0JKw05yLJNaepo0WA54l+rZRDs6tabNLHioWxbWDIfPU4dbCQd5FoZgqWZaqhqpybpA8EehmksQ6/KWQEQ7P+TefI3Zd4P63olqkc1a6q2SdzwcqW7xDg3TMRfZXjBXbf8qNskQuqcaJvC+VtbatO8ah9l3kvVbVirNnD5JWA8mwlxM0thBVB1uz2555kTpuBCid6NydysqrONNlCB3OuLFC+cpbAcOTuS4DlsHaN0Ixy/bEcuacA0CzUKKpurUpHQoTjviaszbOIQYliXCoTCQk9ZZVJXmRhyUhCrHNQi4K1NhJDswMdc/WFeJnkJSHGWDIND7krlJEEWVgykpAQYywpYM1u90fbfKvy2Et2AAHePVP31GDV8LZVF2btL65mL9oggaV+dhe4XqvleuF8fT19ogTvnql/OrxNc4OgYQqLLXWbR30lrHYKkOvOkOvOaGb2MXw0vnJh07/6FH2wEGoVxo8nxCZlpH/9WXLDWaXdD2RhJR28ly6b9L+AqiBQ3t6OGJIN/LR7/m620OFZsBegMPXziaIbSjJRpMEJi+XKHviJ3HoB6gjT0umq29sJh9UzepuHz2fOWDxf78G7N9XN7h/vijZwGtoP15eb5/vxULn5fPdKVQV+QC2NhnfHAggAD5z/tw5wXFyr2fBpaC2W94fDghkgMSwr6BQxJBtqFLyb4ko9TIkbaxK8F14Jtf+yL/ckb/NCg0o5qA0xsHXVrpM5X8ZcsAIAlIPaVN3n5qxegECif+uqxmH+DWf9f54CEBL9Wl6fj1CS0qCExftpcmeFb6eic5Ogs4iOyDS/IvwNCRGr+QAM63hlrfPdTYCssAt1IlDzyC2pH0+o1JZn8X7nK2sBAJllcyut4B3P5frXnIZKrMmlFwX/Ed5H2//5u3veTsAGlO6CAWXzblKSN088GpSwOJuPEzxbcAQJMc4J6EkZRk9Xsb+8xvXGBiFACNrcwJy18C7S8/lOvHNjXbmXYl3hgePlPwX3WmhUYS2NzAUrueGsYAZzI9CghMX7GN5DBb5LnfI6jJV9uXmudzcFxmfTexo/vQvREZzV65i71v3RNsc/VxG3tFT0rGv0B//W867/bg10l6Pbm767F0lRcTav8/X1rvdulDgoDW3wLlDu+lXvtiHQbdEcgFD33FDBJBVJVRvfGYM01fMeyr1wb91v5V1yMHArAHT/zEEMKgADtzK8PjrUyLGh0rCERaCg3LSSc5FAzAmbPmOmjxbRR4t4X4hXtI+mjxWXW1goBT/6ChSYYN7JHC2ue0UE77dAn1zVElWBJrhrTRRpUF0halCiJg1b6AAUyxY5kRAjHPOILwX/i4xjTys6ZVQ9xXG84H6OpCiDQs1WOKeXd7J1hPdXCDfIERxqGloQ23A0qBYLagi8e8VkkDpeEnSWLXKx5fEUAAqxJmKeCELICZLhq7sK8hRTeVYcHnBBsrs6hWSd/uqVuFHWzxqUsAAA2tn9BYdp39LDQU7o7q93C86lxJDsUGd5RIXjHRoJYSCYy/ZrJyiGOVsW6NS6XV2/uCowzkleK3OurOrdFF0rCtPHq3SgFEvnBcu9odLQhKUa1V41qWu5E/Yx70/XYnhQx4pdb24E5QMdwxujRK5EYIVzIs15vt5Tedg1f3e5nxmojIGLpFT0sOTmc8If7m/2cMWuqjerDCzg+XJ35UH3V7uFjvhGoEGNsQSMH9xB7S1gz1vLpn7v/fmIMiebc5HuL3YGBkkQ6J8boujdXPRC9cSurg+30vsLXR9s4V2kontTcnu+59sDAADluE6VsTqwdhVhTuxP/srkW3k/4/pgS2AiWsUWV5nTRjGgFbUt3/vdQYijiptbkDvyvUtCgtU0XBqmaTJ9osQ86iv2kr3aUQRq/9bf8M7YyiWu4p4fCmYzmSX/hmpFYOp31mIe9ZXQ91WCZpkytj6GXt0C4rxUSY8PmdPmawVaGPBOjf2rT1ZdeaePF5fe/iVX6Lx2IxzFskzMyVLlmA6Nfr9f0k8g7qCvvPJKvOsQfdBGWtXYjryH5h0+3k9DJUb0b506f6JuVj9YxV+UPmNBm+jxTo3Vd3YW/EiRVLX6nu6czccWOADLIeka5ZgOqV9OqurxDHFUNb4jZ/GwRQHRKIe1Tft5BkQgJDC8U4ZqfGfBmxRN16rv7MKctrBFTqjCif6tjJ/cibU1QSVO3Nw8cXJzSETDbLFk4k5DG7zLJAiysGQk4f8DAAD//4o6QkjyVO7sAAAAAElFTkSuQmCC"
    mediatype: "img/png"
  install:
    spec:
      clusterPermissions:
      - rules:
        - apiGroups:
          - ""
          resources:
          - secrets
          - pods
          - pods/exec
          - pods/log
          - services
          - configmaps
          verbs:
          - create
          - delete
          - get
          - list
          - patch
          - update
          - watch
        - apiGroups:
          - apps
          - route.openshift.io
          - networking.k8s.io
          resources:
          - deployments
          - daemonsets
          - replicasets
          - statefulsets
          - routes
          - routes/custom-host
          - ingresses
          verbs:
          - create
          - delete
          - get
          - list
          - patch
          - update
          - watch
        - apiGroups:
          - apimon.otc-service.com
          resources:
          - grafanas
          - grafanas/status
          - grafanas/finalizers
          verbs:
          - create
          - delete
          - get
          - list
          - patch
          - update
          - watch
        - apiGroups:
          - apimon.otc-service.com
          resources:
          - alerta
          - alerta/status
          - alerta/finalizers
          verbs:
          - create
          - delete
          - get
          - list
          - patch
          - update
          - watch
        - apiGroups:
          - authentication.k8s.io
          resources:
          - tokenreviews
          verbs:
          - create
        - apiGroups:
          - authorization.k8s.io
          resources:
          - subjectaccessreviews
          verbs:
          - create
        serviceAccountName: default
      deployments:
      - name: apimon-operator-controller-manager
        spec:
          replicas: 1
          selector:
            matchLabels:
              control-plane: controller-manager
          strategy: {}
          template:
            metadata:
              labels:
                control-plane: controller-manager
            spec:
              containers:
              - args:
                - --secure-listen-address=0.0.0.0:8443
                - --upstream=http://127.0.0.1:8080/
                - --logtostderr=true
                - --v=10
                image: gcr.io/kubebuilder/kube-rbac-proxy:v0.5.0
                name: kube-rbac-proxy
                ports:
                - containerPort: 8443
                  name: https
                resources: {}
              - args:
                - --metrics-addr=127.0.0.1:8080
                - --enable-leader-election
                - --leader-election-id=apimon-operator
                env:
                - name: ANSIBLE_GATHERING
                  value: explicit
                image: quay.io/opentelekomcloud/apimon-operator:0.0.11
                name: manager
                resources: {}
              terminationGracePeriodSeconds: 10
      permissions:
      - rules:
        - apiGroups:
          - ""
          resources:
          - configmaps
          verbs:
          - get
          - list
          - watch
          - create
          - update
          - patch
          - delete
        - apiGroups:
          - ""
          resources:
          - events
          verbs:
          - create
          - patch
        serviceAccountName: default
    strategy: deployment
  installModes:
  - supported: true
    type: OwnNamespace
  - supported: true
    type: SingleNamespace
  - supported: true
    type: MultiNamespace
  - supported: true
    type: AllNamespaces
  keywords:
  - apimon
  - monitoring
  - executor
  - scheduler
  - grafana
  - alerta
  links:
  - name: Apimon Operator
    url: https://github.com/opentelekomcloud-infra/apimon-operator
  maintainers:
  - email: Kristian.Kucerak@t-systems.com
    name: Kristian Kucerak
  maturity: alpha
  provider:
    name: Open Telekom Cloud
  version: 0.0.11
