# permissions for end users to view alerta.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: alerta-viewer-role
rules:
- apiGroups:
  - apimon.otc-service.com
  resources:
  - alerta
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - apimon.otc-service.com
  resources:
  - alerta/status
  verbs:
  - get
