# permissions for end users to view alerta-webaddons.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: alerta-webaddon-viewer-role
rules:
- apiGroups:
  - apimon.otc-service.com
  resources:
  - alerta-webaddons
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - apimon.otc-service.com
  resources:
  - alerta-webaddons/status
  verbs:
  - get
