# permissions for end users to view apimons.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: apimon-viewer-role
rules:
- apiGroups:
  - apimon.otc-service.com
  resources:
  - apimons
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - apimon.otc-service.com
  resources:
  - apimons/status
  verbs:
  - get
