apiVersion: operators.coreos.com/v1alpha1
kind: ClusterServiceVersion
metadata:
  annotations:
    alm-examples: '[]'
    capabilities: Basic Install
    operators.operatorframework.io/builder: operator-sdk-v1.2.0
    operators.operatorframework.io/project_layout: ansible.sdk.operatorframework.io/v1
  name: apimon-operator.vX.Y.Z
  namespace: placeholder
spec:
  apiservicedefinitions: {}
  customresourcedefinitions: {}
  description: Apimon operator Open Telekom Cloud
  displayName: apimon-operator
  icon:
  - base64data: ""
    mediatype: ""
  install:
    spec:
      deployments: null
    strategy: ""
  installModes:
  - supported: false
    type: OwnNamespace
  - supported: false
    type: SingleNamespace
  - supported: false
    type: MultiNamespace
  - supported: true
    type: AllNamespaces
  keywords:
  - apimon
  - monitoring
  - executor
  - scheduler
  - grafana
  - alerta
  links:
  - name: Apimon Operator
    url: https://apimon-operator.domain
  maintainers:
  - email: Kristian.Kucerak@t-systems.com
    name: Kristian Kucerak
  maturity: alpha
  provider:
    name: Open Telekom Cloud
  version: 0.0.0
