# This kustomization.yaml is not intended to be run by itself,
# since it depends on service name and namespace that are out of this kustomize package.
# It should be run by config/default
resources:
- bases/apimon.otc-service.com_grafanas.yaml
- bases/apimon.otc-service.com_alerta.yaml
- bases/apimon.otc-service.com_alerta-webaddons.yaml
# +kubebuilder:scaffold:crdkustomizeresource
