---
# defaults file for Grafana
state: present
name: "apimon-{{ ansible_operator_meta.name }}"
instance: "{{ name }}"
config_revision: 0
count: 2
renderer_image: grafana/grafana-image-renderer
image: grafana/grafana
plugins: blackmirror1-singlestat-math-panel,snuids-trafficlights-panel

secret: grafana-secret
config: grafana-config
config_ldap: grafana-config-ldap
config_ldap_ca_cert: grafana-config-ldap-ca-cert 

ldap_server_ip: ''
ldap_server_name: ''

fqdn: grafana.apimon.otc-service.com

cluster_issuer: ''
ssl_cert: ''

renderer_resources:
  limits:
    cpu: 500m
    memory: 500Mi
resources:
  limits:
    cpu: 500m
    memory: 500Mi
  requests:
    cpu: 100m
    memory: 100Mi
