---
# defaults file for Alerta
state: present
name: "apimon-{{ ansible_operator_meta.name }}"
instance: "{{ name }}"
config_revision: 0
count: 2
image: alerta/alerta-web

secret: alerta-secret
config: alerta-config
ldap_server_ip: ''
ldap_server_name: ''
fqdn: alerta.apimon.otc-service.com

cluster_issuer: ''
ssl_cert: ''

resources:
  limits:
    cpu: 500m
    memory: 500Mi
  requests:
    cpu: 100m
    memory: 100Mi
